# Generated by Django 6.0.1 on 2026-04-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issue', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_points', to='farm_data.farmerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
