# Generated by Django 5.2.13 on 2026-04-17 13:13

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("record_key", models.CharField(db_index=True, max_length=150)),
                (
                    "mode",
                    models.CharField(
                        choices=[("historical", "Historical"), ("future", "Future")],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("season", models.CharField(blank=True, max_length=30, null=True)),
                ("window_index", models.IntegerField(blank=True, null=True)),
                (
                    "window_label",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("empty", "Empty"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source_sensor",
                    models.CharField(
                        choices=[
                            ("S2", "Sentinel-2"),
                            ("S1_FALLBACK", "Sentinel-1 fallback"),
                            (
                                "S2_WITH_S1_SUPPORT",
                                "Sentinel-2 with Sentinel-1 support",
                            ),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="UNAVAILABLE",
                        max_length=30,
                    ),
                ),
                (
                    "source_collection",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("fallback_used", models.BooleanField(default=False)),
                ("cloud_threshold", models.FloatField(default=90.0)),
                ("mean_cloud_cover", models.FloatField(blank=True, null=True)),
                ("valid_pixel_fraction", models.FloatField(blank=True, null=True)),
                ("confidence", models.CharField(blank=True, default="", max_length=40)),
                ("selected_item_ids", models.JSONField(blank=True, default=list)),
                ("summary_cards", models.JSONField(blank=True, default=dict)),
                ("run_stats", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("mean_ndvi", models.FloatField(blank=True, null=True)),
                ("mean_ndmi", models.FloatField(blank=True, null=True)),
                ("mean_awei", models.FloatField(blank=True, null=True)),
                ("analysis_type", models.CharField(db_index=True, max_length=60)),
                (
                    "rast",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("srid", models.IntegerField(default=4326)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("band_count", models.IntegerField(default=1)),
                ("nodata", models.FloatField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("style_config", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mode", "start_date", "record_key", "analysis_type"],
                "indexes": [
                    models.Index(
                        fields=["run_id"], name="imagery_ana_run_id_614599_idx"
                    ),
                    models.Index(
                        fields=["record_key"], name="imagery_ana_record__4ee4fc_idx"
                    ),
                    models.Index(
                        fields=["mode", "year", "season"],
                        name="imagery_ana_mode_81a594_idx",
                    ),
                    models.Index(
                        fields=["status"], name="imagery_ana_status_cc570a_idx"
                    ),
                    models.Index(
                        fields=["analysis_type"], name="imagery_ana_analysi_7a32c6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "analysis_type"),
                        name="uniq_analysisrecord_run_analysis_type",
                    )
                ],
            },
        ),
    ]
